# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# Caching so the next build will be fast too.
cache:
  timeout: 900  # 15 minutes
  directories:
  - $HOME/.stack
  - $HOME/.cabal/packages

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar

# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.
#
# If you need to have different apt packages for each combination in the
# matrix, you can use a line such as:
#     addons: {apt: {packages: [libfcgi-dev,libgmp-dev]}}
matrix:
  include:
  # The Stack builds. We can pass in arbitrary Stack arguments via the ARGS
  # variable, such as using --stack-yaml to point to a different file.
  # Nightly builds are allowed to fail
  - env: BUILD=stack ARGS=""
    compiler: ": #stack 8.0.1 OSX"
    os: osx

  allow_failures:
  - env: BUILD=stack ARGS="--resolver nightly"

before_install:
- unset CC
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=~/.local/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

install:
- set -ex
- stack +RTS -N2 -RTS --skip-ghc-check --no-terminal $ARGS setup
- stack +RTS -N2 -RTS --skip-ghc-check --no-terminal $ARGS build --only-snapshot
- set +ex

script:
- set -ex
- stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
- set +ex

# Clean up the test artifacts so we don't have binaries generating .tix files
# on end-user machines. Also strip the binary of debugging symbols to reduce
# final filesize. Finally, tar it up and ship it!
before_deploy:
- export BARTLETT_VERSION=$(grep version bartlett.cabal | head -1 | awk -F: '{ print $2 }' | tr -d '[:space:]')
- stack clean && stack build --copy-bins && strip "${HOME}/.local/bin/bartlett"
  && tar czvf -C "${HOME}/.local/bin/" "bartlett-static-${BARTLETT_VERSION}.tar.gz"

deploy:
  provider: releases
  skip_cleanup: true
  file: "$TRAVIS_BUILD_DIR/bartlett-static-${BARTLETT_VERSION}.tar.gz"
  on:
    repo: Nike-Inc/bartlett
    tags: true
